<?php
$title = 'Firma löschen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Filiale
    <b><?php echo $company['name']; ?></b> 
    (<?php echo $company['street'] . ', ' . $company['zip'] . ' ' . $company['place'] ; ?>) wirklich löschen?
</p>
<?php
$url = $this->url('company', array(
    'action' => 'delete',
    'id' => $this->id,
        ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $company['id']; ?>" />
        <input type="submit" name="del" value="Ja" />
        <input type="submit" name="del" value="Nein" />
    </div>
</form>