<?php
$title = 'Filiale löschen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Filiale
    <b><?php echo $branch['name']; ?></b> 
    (<?php echo $branch['email']; ?>) wirklich löschen?
</p>
<?php
$url = $this->url('branch', array(
    'action' => 'delete',
    'id' => $this->id,
        ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $branch['id']; ?>" />
        <input type="submit" name="del" value="Ja" />
        <input type="submit" name="del" value="Nein" />
    </div>
</form>