<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Benutzer bearbeiten';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 /*$form = $this->form;
 $form->setAttribute('action', $this->url('company', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('email'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 */

$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'update')));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

